import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold text-red-900 underline hm_">
          Code Hustler
        </h1>
        <Image
          className="my-4 rounded-xl"
          src="/home.avif"
          width={200}
          height={150}
          alt="/"
        />

        <p className={styles.description}>Code Hustler by Coder</p>
        
        <div className="mt-8 text-center m">
        <h3 className="font-bold">BlogPost 1 Create By User 1</h3>
        <p className="mb-4">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, sit?</p>
        <h3 className="font-bold">BlogPost 2 Create By User 2</h3>
        <p className="mb-4">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, sit?</p>
        <h3 className="font-bold">BlogPost 3 Create By User 3</h3>
        <p className="mb-4">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, sit?</p>
        <h3 className="font-bold">BlogPost 3 Create By User 4</h3>
        <p className="mb-4">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, sit?</p>
        </div>
      </main>
    </div>
  );
}
